<?php
require_once __DIR__.'/bootstrap.lib.php';
require_once __DIR__.'/migrations.lib.php';
require_once __DIR__.'/cgnat.lib.php';
ipv6RequireMkAuthLogin();
$conn=new mysqli('127.0.0.1','root','vertrigo','mkradius');
ipv6RunMigrations($conn);
$downloadId=(int)($_GET['download_csv']??0);
if($downloadId>0){
 header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="cgnat-'.$downloadId.'-conexoes.csv"');
 $out=fopen('php://output','w');fputs($out,"\xEF\xBB\xBF");fputcsv($out,array('Login','Inicio da conexao','Fim da conexao','Inicio da vigencia','Fim da vigencia','IP privado','IP publico','Porta inicial','Porta final'),';');
 $stmt=$conn->prepare("SELECT username,connection_start,connection_end,effective_start,effective_end,private_ip,public_ip,port_start,port_end FROM cgnat_connection_archive WHERE profile_id=? ORDER BY effective_start");$stmt->bind_param('i',$downloadId);$stmt->execute();$res=$stmt->get_result();while($r=$res->fetch_assoc())fputcsv($out,$r,';');$stmt->close();
 $stmt=$conn->prepare("SELECT r.username,r.acctstarttime,r.acctstoptime,IF(r.acctstarttime>v.started_at,r.acctstarttime,v.started_at),NOW(),r.framedipaddress,m.public_ip,m.port_start,m.port_end FROM cgnat_profile_periods v INNER JOIN radacct r ON r.acctstarttime<NOW() AND (r.acctstoptime IS NULL OR r.acctstoptime>v.started_at) LEFT JOIN cgnat_mappings m ON m.profile_id=v.profile_id AND m.private_ip=r.framedipaddress WHERE v.profile_id=? AND v.ended_at IS NULL AND v.superseded_at IS NULL ORDER BY r.acctstarttime");$stmt->bind_param('i',$downloadId);$stmt->execute();$res=$stmt->get_result();while($r=$res->fetch_row())fputcsv($out,$r,';');$stmt->close();fclose($out);exit;
}
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  $id=(int)($_POST['profile_id']??0);
  if($id<1)throw new RuntimeException('Perfil CGNAT invalido.');
  if(isset($_POST['activate']) || isset($_POST['activate_retro'])){
   $effectiveDate=trim($_POST['effective_date']??'');
   cgnatActivateProfile($conn,$id,$effectiveDate);$message='CGNAT #'.$id.' ativado no cruzamento'.($effectiveDate!==''?' com vigencia retroativa desde '.date('d/m/Y H:i',strtotime($effectiveDate)):'').'. Clientes online e conexoes dentro desta vigencia passam a usar este mapeamento junto com os demais blocos ativos; os periodos substituidos continuam preservados para auditoria.';
  }elseif(isset($_POST['deactivate'])){
   cgnatDeactivateProfile($conn,$id);$message='CGNAT #'.$id.' desativado. O periodo foi encerrado e preservado no historico.';
  }elseif(isset($_POST['delete'])){
   $check=$conn->query('SELECT active FROM cgnat_profiles WHERE id='.$id)->fetch_assoc();
   if(!$check)throw new RuntimeException('Perfil nao encontrado.');
   if((int)$check['active']===1)throw new RuntimeException('Marque outro CGNAT como padrao antes de excluir o perfil atual.');
   if(!$conn->query('UPDATE cgnat_profiles SET deleted_at=NOW() WHERE id='.$id))throw new RuntimeException($conn->error);
   $message='CGNAT #'.$id.' arquivado. Mapeamentos e relatorios permanecerao guardados por dois anos.';
  }
 }catch(Exception $e){$conn->rollback();$error=$e->getMessage();}
}
$profiles=array();
$sql="SELECT p.*,COUNT(DISTINCT m.id) mapping_count,MIN(m.private_ip) first_private,MAX(m.private_ip) last_private,MIN(CASE WHEN v.superseded_at IS NULL THEN v.started_at END) first_started,MAX(CASE WHEN v.ended_at IS NULL AND v.superseded_at IS NULL THEN v.started_at END) current_started,MAX(CASE WHEN v.superseded_at IS NULL THEN v.ended_at END) last_ended FROM cgnat_profiles p LEFT JOIN cgnat_mappings m ON m.profile_id=p.id LEFT JOIN cgnat_profile_periods v ON v.profile_id=p.id GROUP BY p.id ORDER BY p.created_at DESC,p.id DESC";
$rows=$conn->query($sql);if($rows)while($row=$rows->fetch_assoc())$profiles[]=$row;
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!DOCTYPE html><html lang="pt-BR" class="has-navbar-fixed-top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="../../estilos/mk-auth.css" rel="stylesheet"><link href="../../estilos/font-awesome.css" rel="stylesheet"><link href="addon-theme.css?v=20260809" rel="stylesheet"><script src="../../scripts/jquery.js"></script><script src="../../scripts/mk-auth.js"></script>
<style>html,body{overflow-x:hidden}.wrap{position:relative;left:50%;transform:translateX(-50%);width:calc(100vw - 32px);max-width:1800px;box-sizing:border-box;margin:20px 0;background:#f8fbff;color:#19324d;padding:20px;border:1px solid #bfdbef;border-radius:12px;box-shadow:0 8px 24px rgba(15,23,42,.08)}.nav{display:flex;gap:8px;flex-wrap:wrap;margin:15px 0 22px}.nav a{padding:10px 14px;border-radius:7px;background:#e1f1fb;color:#173b57;text-decoration:none;border:1px solid #b8dcef;font-weight:600}.nav a.active{background:#38a9dc;color:#fff}.card{background:#fff;border:1px solid #bdd8ea;border-radius:10px;padding:18px}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th{background:#19324d;color:#fff;padding:11px;text-align:left}td{padding:10px;border-bottom:1px solid #d8e6ef;vertical-align:middle}tbody tr:nth-child(odd){background:#f4f9fc}.badge{display:inline-block;padding:5px 9px;border-radius:20px;background:#e5edf3;color:#526d82;font-weight:700}.badge.active{background:#d9f8e9;color:#147348}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions form{margin:0}.btn{border:0;border-radius:7px;padding:9px 12px;color:#fff;background:#208fc5;cursor:pointer;font-weight:700}.btn.danger{background:#d94b4b}.btn[disabled]{opacity:.45;cursor:not-allowed}.alert,.ok{padding:12px;border-radius:7px;margin:12px 0}.alert{background:#fff1f1;border:1px solid #e56262;color:#842929}.ok{background:#e9fff4;border:1px solid #35b77b;color:#155f42}.empty{text-align:center;padding:35px;color:#526d82}@media(max-width:700px){.wrap{width:calc(100vw - 18px)}}</style></head><body>
<?php ob_start(); include('../../topo.php'); echo ipv6CleanMkAuthDiagnostic(ob_get_clean()); ?><div class="container"><main class="wrap"><h2>Historico de CGNAT gerados</h2><div class="nav"><a href="ipv6.php">Painel e logs</a><a href="mikrotik.php">Scripts MikroTik</a><a href="cgnat.php">CGNAT</a><a class="active" href="cgnat_history.php">Historico de CGNAT</a><a href="import.php">Importar mapeamento</a></div>
<?php if($error):?><div class="alert"><?=h($error)?></div><?php endif;?><?php if($message):?><div class="ok"><?=h($message)?></div><?php endif;?>
<section class="card" style="margin-bottom:16px"><h3>Aplicar CGNAT com data retroativa</h3><p>Use quando o CGNAT ja estava em producao antes de ser cadastrado no MK-Auth. O painel recalculara as conexoes desde a data informada, limitado aos ultimos dois anos.</p><form method="post" onsubmit="return confirm('ATENCAO: este mapeamento substituira o cruzamento das conexoes desde a data informada. Os periodos anteriores permanecerao preservados para auditoria. Confirma?')" style="display:flex;gap:12px;align-items:end;flex-wrap:wrap"><label style="display:grid;gap:5px;font-weight:700">CGNAT<select name="profile_id" required style="min-width:260px;padding:9px;border:1px solid #9ac6df;border-radius:7px"><option value="">Selecione o CGNAT</option><?php foreach($profiles as $retro):if($retro['deleted_at'])continue;?><option value="<?=$retro['id']?>"><?=h(strtoupper($retro['name']).' | '.$retro['private_cidr'].' > '.$retro['public_cidr'])?></option><?php endforeach;?></select></label><label style="display:grid;gap:5px;font-weight:700">Valido desde<input type="datetime-local" name="effective_date" required min="<?=date('Y-m-d\TH:i',strtotime('-2 years'))?>" max="<?=date('Y-m-d\TH:i')?>" style="min-width:220px;padding:8px;border:1px solid #9ac6df;border-radius:7px"></label><button class="btn" name="activate_retro" value="1">Aplicar retroativamente</button></form></section>
<section class="card"><p>Todos os perfis marcados como <strong>Ativos no cruzamento</strong> sao usados simultaneamente nas novas conexoes, desde que suas redes privadas nao se sobreponham. Os periodos de vigencia ficam registrados para que conexoes antigas continuem sendo cruzadas com o CGNAT correto.</p><div class="table-wrap"><table><thead><tr><th>Gerado em</th><th>CGNAT</th><th>Rede privada</th><th>Rede publica</th><th>Portas</th><th>Clientes/IP</th><th>Total clientes</th><th>Vigencia</th><th>Status</th><th>Acoes</th></tr></thead><tbody>
<?php if(!$profiles):?><tr><td colspan="10" class="empty">Nenhum mapeamento CGNAT foi salvo ainda.</td></tr><?php endif;?>
<?php foreach($profiles as $p):?><tr><td><?=h(date('d/m/Y H:i',strtotime($p['created_at'])))?></td><td><strong><?=h(strtoupper($p['name']))?></strong><br>#<?=$p['id']?> - <?=h($p['source']==='generated'?'Gerado':'Importado')?></td><td><?=h($p['private_cidr'])?><br><small><?=number_format((int)$p['mapping_count'],0,',','.')?> IPs mapeados</small></td><td><?=h($p['public_cidr'])?></td><td><?=number_format((int)$p['ports_per_client'],0,',','.')?><br><small><?=$p['first_port']?>-<?=$p['last_port']?></small></td><td><?=$p['clients_per_public']?></td><td><?=number_format((int)$p['mapping_count'],0,',','.')?></td><td><?php if($p['first_started']):?>Desde <?=h(date('d/m/Y H:i',strtotime($p['first_started'])))?><?php endif;?><?php if($p['active']&&$p['current_started']):?><br><strong>Ativo desde <?=h(date('d/m/Y H:i',strtotime($p['current_started'])))?></strong><?php elseif($p['last_ended']):?><br>Ate <?=h(date('d/m/Y H:i',strtotime($p['last_ended'])))?><?php endif;?></td><td><span class="badge <?=$p['active']?'active':''?>"><?=$p['active']?'Ativo no cruzamento':($p['deleted_at']?'Arquivado por 2 anos':'Historico')?></span></td><td><div class="actions"><a class="btn" href="?download_csv=<?=$p['id']?>">Baixar relatorio CSV</a><?php if(!$p['deleted_at']):?><form method="post" onsubmit="return confirm('ATENCAO: este CGNAT sera ativado junto com os demais blocos ativos. Redes privadas sobrepostas serao recusadas para evitar cruzamento incorreto. Confirma?')"><input type="hidden" name="profile_id" value="<?=$p['id']?>"><button class="btn" name="activate" value="1" <?=$p['active']?'disabled':''?>>Ativar no cruzamento</button></form><form method="post" onsubmit="return confirm('Este CGNAT sera arquivado, nao apagado. Mapeamentos e conexoes permanecerao disponiveis para relatorio por dois anos. Confirma?')"><input type="hidden" name="profile_id" value="<?=$p['id']?>"><button class="btn danger" name="delete" value="1" <?=$p['active']?'disabled title="Desative este perfil na configuracao do painel antes de arquivar"':''?>>Arquivar</button></form><?php endif;?></div></td></tr><?php endforeach;?>
</tbody></table></div></section></main></div><?php include('../../baixo.php'); ?><script src="../../menu.js.php"></script><?php if (is_file('../../rodape.php')) { include('../../rodape.php'); } ?></body></html>

