<?php
$addonsClass=file_exists(__DIR__.'/addons.class.php')?__DIR__.'/addons.class.php':dirname(__DIR__).'/addons.class.php'; include($addonsClass);
require_once __DIR__.'/migrations.lib.php'; require_once __DIR__.'/retention.lib.php';
if(session_status()===PHP_SESSION_NONE){session_name('mka');session_start();} if(!isset($_SESSION['mka_logado'])&&!isset($_SESSION['MKA_Logado']))exit('Acesso negado');
$conn=new mysqli('127.0.0.1','root','vertrigo','mkradius'); ipv6RunMigrations($conn); $saved='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $enabled=isset($_POST['enabled'])?'1':'0'; $private=trim($_POST['private_network']??''); $public=trim($_POST['public_network']??''); $ratio=(string)(int)($_POST['ratio']??32); $ros=($_POST['routeros']??'7')==='6'?'6':'7';
 foreach(array('cgnat_enabled'=>$enabled,'cgnat_private_network'=>$private,'cgnat_public_network'=>$public,'cgnat_ratio'=>$ratio,'cgnat_routeros'=>$ros) as $k=>$v) ipv6SaveSetting($conn,$k,$v); $saved='Configuracao CGNAT salva.';
}
$enabled=ipv6GetSetting($conn,'cgnat_enabled','0'); $private=ipv6GetSetting($conn,'cgnat_private_network','100.64.0.0/10'); $public=ipv6GetSetting($conn,'cgnat_public_network',''); $ratio=ipv6GetSetting($conn,'cgnat_ratio','32'); $ros=ipv6GetSetting($conn,'cgnat_routeros','7');
?>
<!DOCTYPE html><html lang="pt-BR" class="has-navbar-fixed-top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="../../estilos/mk-auth.css" rel="stylesheet"><style>.wrap{max-width:1050px;margin:20px auto;background:#eaf7ff;color:#17324d;padding:22px;border:1px solid #b9ddf2;border-radius:12px}.nav{display:flex;gap:8px;flex-wrap:wrap;margin:15px 0 22px}.nav a{padding:10px 14px;border-radius:7px;background:#d4efff;color:#17324d;text-decoration:none}.nav a.active{background:#8ed2f2}.card{background:#fff;border:1px solid #b9ddf2;border-radius:10px;padding:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid label{font-weight:bold}.grid input,.grid select{width:100%;padding:10px;box-sizing:border-box;border:1px solid #9bcde8;border-radius:6px}.save{margin-top:16px;background:#4fb8e8;color:#fff;border:0;padding:10px 18px;border-radius:7px}.ok{background:#d9f9e5;border:1px solid #71cc94;padding:10px;margin-bottom:12px}.note{background:#fff4cf;border:1px solid #e4c663;padding:12px;margin-top:15px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body><?php include('../../topo.php'); ?><div class="container"><div class="wrap"><h2>Configura&ccedil;&atilde;o CGNAT</h2><div class="nav"><a href="ipv6.php">Painel e logs</a><a href="mikrotik.php">Scripts MikroTik</a><a class="active" href="cgnat.php">CGNAT</a><a href="ipv6.php?module=import">Importar mapeamento</a></div><?php if($saved):?><div class="ok"><?=$saved?></div><?php endif;?><div class="card"><form method="post"><p><label><input type="checkbox" name="enabled" value="1" <?=($enabled==='1'?'checked':'')?>> Ativar modulo CGNAT opcional</label></p><div class="grid"><div><label>Rede privada inicial</label><input name="private_network" value="<?=htmlspecialchars($private)?>" placeholder="100.64.0.0/10"></div><div><label>Prefixo publico</label><input name="public_network" value="<?=htmlspecialchars($public)?>" placeholder="200.200.200.0/24"></div><div><label>Privados por IP publico</label><select name="ratio"><?php foreach(array(4,8,16,32,64,128) as $n):?><option value="<?=$n?>" <?=((int)$ratio===$n?'selected':'')?>><?=$n?> clientes</option><?php endforeach;?></select></div><div><label>RouterOS</label><select name="routeros"><option value="6" <?=($ros==='6'?'selected':'')?>>Versao 6</option><option value="7" <?=($ros==='7'?'selected':'')?>>Versao 7</option></select></div></div><button class="save">Salvar configura&ccedil;&atilde;o</button></form><div class="note">Salvar aqui ainda n&atilde;o aplica regras no MikroTik. A gera&ccedil;&atilde;o e a revis&atilde;o do script ser&atilde;o uma etapa separada para evitar NAT incorreto em produ&ccedil;&atilde;o.</div></div></div></div><?php include('../../baixo.php'); ?><script src="../../menu.js.php"></script><?php include('../../rodape.php'); ?></body></html>
